=== DreamLogics/gtkmathview/config/font-configuration.dtd
<?xml version="1.0" encoding="iso8859-1"?>
<!ELEMENT font-configuration (font|map)*>

<!ELEMENT font EMPTY>
<!ATTLIST font
  type      (x|ps) #REQUIRED

  mode      (any|text|math) #IMPLIED

  family    CDATA #IMPLIED
  style     (normal|italic) #IMPLIED
  weight    (normal|bold) #IMPLIED
  size      CDATA #IMPLIED

  mapping   CDATA #IMPLIED

  x-foundry  CDATA #IMPLIED
  x-family   CDATA #IMPLIED
  x-weight   CDATA #IMPLIED
  x-slant    CDATA #IMPLIED
  x-width    CDATA #IMPLIED
  x-style    CDATA #IMPLIED
  x-pixels   CDATA #IMPLIED
  x-points   CDATA #IMPLIED
  x-hres     CDATA #IMPLIED
  x-vres     CDATA #IMPLIED
  x-spacing  CDATA #IMPLIED
  x-avgwidth CDATA #IMPLIED
  x-registry CDATA #IMPLIED
  x-encoding CDATA #IMPLIED

  ps-name   CDATA #IMPLIED
  ps-file   CDATA #IMPLIED
>

<!ELEMENT map (single|range|multi|stretchy)*>
<!ATTLIST map
  id      CDATA #REQUIRED
>

<!ELEMENT single EMPTY>
<!ATTLIST single
  name CDATA #IMPLIED
  code CDATA #IMPLIED
  index CDATA #IMPLIED
>

<!ELEMENT range EMPTY>
<!ATTLIST range
  first CDATA #REQUIRED
  last  CDATA #REQUIRED
  offset CDATA #REQUIRED
>

<!ELEMENT multi EMPTY>
<!ATTLIST multi
  first CDATA #REQUIRED
  last  CDATA #REQUIRED
  index CDATA #REQUIRED
>  

<!ELEMENT stretchy (simple, compound?)>
<!ATTLIST stretchy
  name CDATA #IMPLIED
  code CDATA #IMPLIED
  direction (vertical|horizontal|both) #REQUIRED
>

<!ELEMENT simple EMPTY>
<!ATTLIST simple index CDATA #REQUIRED>

<!ELEMENT compound EMPTY>
<!ATTLIST compound index CDATA #REQUIRED>

=== DreamLogics/gtkmathview/config/font-configuration-mt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE font-configuration SYSTEM "font-configuration.dtd">
<!--
Copyright (C) 2000, Luca Padovani (luca.padovani@cs.unibo.it).

This file is part of GtkMathView, a Gtk widget for MathML.

GtkMathView is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

GtkMathView is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GtkMathView; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

For details, see the GtkMathView World-Wide-Web page,
http://cs.unibo.it/~lpadovan/mml-widget, or send a mail to
(luca.padovani@cs.unibo.it)
-->

<font-configuration>
  <font type="ps" mode="math" map="mt-extra"
	family="mtextra" style="normal" weight="normal"
	ps-file="mtextra.pfa"
	/>

  <map id="mt-extra">
    <single code="0x2A3F" index="67"/>
    <single code="0x2210" index="67"/>
    <single code="0x2A3C" index="70"/>    
    <single code="0x2113" index="108"/>    
    <single code="0x227A" index="112"/>
    <single code="0x227B" index="102"/>
    <single code="0x225C" index="64"/>
    <single code="0x2423" index="124"/>
    <single code="0xFB01" index="241"/>
    <single code="0xFB02" index="241"/>
    <single code="0x25AD" index="88"/>
    <single code="0x301A" index="167"/>
    <single code="0x301B" index="168"/>
    <single code="0x2259" index="65"/>
  </map>
</font-configuration>

=== DreamLogics/gtkmathview/config/font-configuration-euclid.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE font-configuration SYSTEM "font-configuration.dtd">
<!--
Copyright (C) 2000, Luca Padovani (luca.padovani@cs.unibo.it).

This file is part of GtkMathView, a Gtk widget for MathML.

GtkMathView is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

GtkMathView is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GtkMathView; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

For details, see the GtkMathView World-Wide-Web page,
http://cs.unibo.it/~lpadovan/mml-widget, or send a mail to
(luca.padovani@cs.unibo.it)
-->

<font-configuration>
  <font type="ps" mode="math" map="euclid-math1"
	family="math1" style="normal" weight="normal"
	ps-file="eumat1.pfa"
	/>

  <font type="ps" mode="math" map="euclid-math2"
	family="math2" style="normal" weight="normal"
	ps-file="eumat2.pfa"
	/>

  <font type="ps" mode="math" map="euclid-fraktur"
	family="fraktur" style="normal" weight="normal"
	ps-file="eufrak.pfa"
	/>

  <map id="euclid-math1">
    <single code="0x21B6" index="209"/>
    <single code="0x21B7" index="208"/>
    <single code="0x21CA" index="197"/>
    <single code="0x21AB" index="205"/>
    <single code="0x21A2" index="177"/>
    <single code="0x21DA" index="201"/>
    <single code="0x21C7" index="194"/>
    <single code="0x21B0" index="203"/>
    <single code="0x219E" index="179"/>
    <single code="0x22B8" index="168"/>
    <single code="0x21AE" index="192"/>
    <single code="0x21CE" index="193"/>
    <single code="0x219A" index="188"/>
    <single code="0x21CD" index="190"/>
    <single code="0x219B" index="189"/>
    <single code="0x21CF" index="191"/>
    <single code="0x21BA" index="211"/>
    <single code="0x21BB" index="210"/>
    <single code="0x21AC" index="204"/>
    <single code="0x21A3" index="176"/>
    <single code="0x21DB" index="200"/>
    <single code="0x21C9" index="195"/>
    <single code="0x21B1" index="202"/>
    <single code="0x21A0" index="178"/>
    <single code="0x21DD" index="206"/>
    <single code="0x22C7" index="230"/>
    <single code="0x22CB" index="224"/>
    <single code="0x22C9" index="226"/>
    <single code="0x229F" index="39"/>
    <single code="0x229B" index="35"/>
    <single code="0x229A" index="34"/>
    <single code="0x229D" index="33"/>
    <single code="0x2296" index="36"/>
    <single code="0x2298" index="37"/>
    <single code="0x229E" index="40"/>
    <single code="0x2214" index="234"/>
    <single code="0x22CC" index="225"/>
    <single code="0x22CA" index="227"/>
    <single code="0x22A1" index="42"/>
    <single code="0x22C6" index="229"/>
    <single code="0x22A0" index="41"/>
    <single code="0x231E" index="133"/>
    <single code="0x231F" index="135"/>
    <single code="0x231C" index="132"/>
    <single code="0x231D" index="134"/>
    <single code="0x22AC" index="150"/>
    <single code="0x22AD" index="151"/>
    <single code="0x22AE" index="152"/>
    <single code="0x22AF" index="153"/>
    <single code="0x2201" index="240"/>
    <single code="0x24C8" index="38"/>
    <single code="0x224A" index="172"/>
    <single code="0x224A" index="172"/>
    <single code="0x2256" index="162"/>
    <single code="0x2251" index="164"/>
    <single code="0x2252" index="165"/>
    <single code="0x2253" index="163"/>
    <single code="0x22A7" index="145"/>
    <single code="0x22A9" index="146"/>
    <single code="0x22AA" index="147"/>
    <single code="0x2041" index="225"/>
    <single code="0x230D" index="134"/>
    <single code="0x230C" index="132"/>
    <single code="0x2720" index="228"/>
    <single code="0x230F" index="135"/>
    <single code="0x230E" index="133"/>
  </map>

  <map id="euclid-math2">
    <single code="0x22BC" index="170"/>
    <single code="0x2306" index="171"/>
    <single code="0x22CE" index="203"/>
    <single code="0x22CF" index="202"/>
    <single code="0x22D2" index="211"/>
    <single code="0x22D3" index="210"/>
    <single code="0x22BB" index="169"/>
    <single code="0x2269" index="153"/>
    <single code="0x22E6" index="0x9e"/>
    <single code="0x22E7" index="159"/>
    <single code="0x0000" index="155"/>
    <single code="0x2A89" index="161"/>
    <single code="0x2A8A" index="162"/>
    <single code="0x2268" index="152"/>
    <single code="0x2268" index="152"/>
    <single code="0x0000" index="154"/>
    <single code="0x2288" index="218"/>
    <single code="0x2288" index="224"/>
    <single code="0x2289" index="219"/>
    <single code="0x2289" index="225"/>
    <single code="0x22E8" index="0xc6"/>
    <single code="0x2AB5" index="196"/>
    <single code="0x22E9" index="0xc7"/>
    <single code="0x2AB6" index="197"/>
    <single code="0x228A" index="214"/>
    <single code="0x228A" index="220"/>
    <single code="0x228B" index="215"/>
    <single code="0x228B" index="221"/>
    <single code="0x22DD" index="131"/>
    <single code="0x22DC" index="130"/>
    <single code="0x22D4" index="227"/>
    <single code="0x22D8" index="140"/>
    <single code="0x2287" index="213"/>
    <single code="0x22D0" index="208"/>
    <single code="0x22D1" index="209"/>
    <single code="0x25C2" index="38"/>
    <single code="0x25B8" index="37"/>
  </map>

  <map id="euclid-fraktur">
    <single code="0x1D51E" index="97"/>
    <single code="0x1D504" index="65"/>
    <single code="0x1D51F" index="98"/>
    <single code="0x1D505" index="66"/>
    <single code="0x1D520" index="99"/>
    <single code="0x0212D" index="67"/>
    <single code="0x1D521" index="100"/>
    <single code="0x1D507" index="68"/>
    <single code="0x1D522" index="101"/>
    <single code="0x1D508" index="69"/>
    <single code="0x1D523" index="102"/>
    <single code="0x1D509" index="70"/>
    <single code="0x1D524" index="103"/>
    <single code="0x1D50A" index="71"/>
    <single code="0x1D525" index="104"/>
    <single code="0x210C" index="72"/>
    <single code="0x1D526" index="105"/>
    <single code="0x2111" index="73"/>
    <single code="0x1D527" index="106"/>
    <single code="0x1D50D" index="74"/>
    <single code="0x1D528" index="107"/>
    <single code="0x1D50E" index="75"/>
    <single code="0x1D529" index="108"/>
    <single code="0x1D50F" index="76"/>
    <single code="0x1D52A" index="109"/>
    <single code="0x1D510" index="77"/>
    <single code="0x1D52B" index="110"/>
    <single code="0x1D511" index="78"/>
    <single code="0x1D52C" index="111"/>
    <single code="0x1D512" index="79"/>
    <single code="0x1D52D" index="112"/>
    <single code="0x1D513" index="80"/>
    <single code="0x1D52E" index="113"/>
    <single code="0x1D514" index="81"/>
    <single code="0x1D52F" index="114"/>
    <single code="0x211C" index="82"/>
    <single code="0x1D530" index="115"/>
    <single code="0x1D516" index="83"/>
    <single code="0x1D531" index="116"/>
    <single code="0x1D517" index="84"/>
    <single code="0x1D532" index="117"/>
    <single code="0x1D518" index="85"/>
    <single code="0x1D533" index="118"/>
    <single code="0x1D519" index="86"/>
    <single code="0x1D534" index="119"/>
    <single code="0x1D51A" index="87"/>
    <single code="0x1D535" index="120"/>
    <single code="0x1D51B" index="88"/>
    <single code="0x1D536" index="121"/>
    <single code="0x1D51C" index="89"/>
    <single code="0x1D537" index="122"/>
    <single code="0x02128" index="90"/>
  </map>
</font-configuration>
